from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('panel_paciente/', views.panel_paciente, name='panel_paciente'),
    path('panel_doctor/', views.panel_doctor, name='panel_doctor'),
    path('panel_recepcionista/', views.panel_recepcionista, name='panel_recepcionista'),
    path('agendar_cita/', views.agendar_cita, name='agendar_cita'),
    path('obtener_doctores/<int:especialidad_id>/', views.obtener_doctores, name='obtener_doctores'),
    path('citas_agendadas/', views.citas_agendadas, name='citas_agendadas'),
    path('registro_paciente/', views.registro_paciente, name='registro_paciente'),
    path('validar_correo/', views.validar_correo, name='validar_correo'),
    path('datos_personales/', views.datos_personales, name='datos_personales'),
    path('pagar_cita/<int:id_cita>/', views.pagar_cita, name='pagar_cita'),
    path('cancelar_cita/<int:id_cita>/', views.cancelar_cita, name='cancelar_cita'),
    path("citas_medico/", views.citas_medico, name="citas_medico"),
    path('generar_receta/<int:id_paciente>/', views.generar_receta, name='generar_receta'),
    path('ver_receta/<int:id_receta>/', views.ver_receta_detalle, name='ver_receta_detalle'),
    path('historial_recetas/', views.historial_recetas, name='historial_recetas'),
    path("solicitar_cancelacion_medico/<int:id_cita>/", views.solicitar_cancelacion_medico, name="solicitar_cancelacion_medico"),
    path("paciente/<int:id_paciente>/", views.datos_paciente_medico, name="datos_paciente_medico"),
    path('atender_cita/<int:id_cita>/', views.atender_cita, name='atender_cita'),
    path('doctor/datos/', views.datos_doctor, name='datos_doctor'),
    path("recepcionista/doctores/", views.gestionar_doctores, name="gestionar_doctores"),
    path("recepcionista/doctor/estado/<int:id_doctor>/",views.cambiar_estado_doctor,name="cambiar_estado_doctor"),
    path("recepcionista/doctor/alta/",views.alta_doctor,name="alta_doctor"),
    path("recepcionista/recepcionistas/", views.gestionar_recepcionistas, name="gestionar_recepcionistas"),
    path("recepcionista/recepcionista/alta/",views.alta_recepcionista,name="alta_recepcionista"),
    path("recepcionista/bitacora_citas/", views.bitacora_citas_recepcionista, name="bitacora_citas_recepcionista"),
    path("cancelar_cita_paciente/<int:id_cita>/", views.cancelar_cita_paciente, name="cancelar_cita_paciente"),
    path("autorizar_cancelacion_medico/<int:id_cita>/", views.autorizar_cancelacion_medico, name="autorizar_cancelacion_medico"),
    path("recepcionista/farmacia/", views.farmacia, name="farmacia"),
    path("recepcionista/farmacia/alta/", views.alta_medicamento, name="alta_medicamento"),
    path("recepcionista/farmacia/editar/<int:id_medicamento>/", views.editar_medicamento, name="editar_medicamento"),
    path("recepcionista/servicios/", views.servicios_recepcionista, name="servicios_recepcionista"),
    path("recepcionista/servicios/alta/", views.alta_servicio, name="alta_servicio"),
    path("recepcionista/servicios/editar/<int:id_servicio>/", views.editar_servicio, name="editar_servicio"),
    path("recepcionista/cobro/", views.cobro_inicio, name="cobro_inicio"),
    path("recepcionista/cobro/<int:id_ticket>/", views.cobro_ticket, name="cobro_ticket"),
    path("recepcionista/cobro/agregar_medicamento/", views.agregar_medicamento_ticket, name="agregar_medicamento_ticket"),
    path("recepcionista/cobro/agregar_servicio/", views.agregar_servicio_ticket, name="agregar_servicio_ticket"),
    path("recepcionista/cobro/pagar/<int:id_ticket>/", views.pagar_ticket, name="pagar_ticket"),
    path("recepcionista/cliente/alta/", views.alta_cliente, name="alta_cliente"),
    path("cobro/resumen/<int:id_ticket>/", views.resumen_ticket, name="resumen_ticket"),

]
